backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/media"
public_folder: "/assets/media"
collections: 
  - name: "article"
    label: "Articles"
    label_singular: "Article"
    folder: "src/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - { label: "Tags", name: "tags", widget: "list", default: ["articles"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image caption", name: "imageAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "gallery"
    label: "Gallery"
    label_singular: "Gallery Image"
    folder: "src/gallery"
    create: true
    slug: "{{fields.date}}-{{fields.image}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      
  - name: "fixtures"
    label: "Fixtures"
    label_singular: "Fixture"
    folder: "src/fixtures"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{team}}-{{opponent}}"
    fields: 
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD/MM/YYYY", time_format: false }
      - label: "Team"
        name: "team"
        widget: "select"
        options:
          - { label: "Mens", value: "MEN" }
          - { label: "Composite", value: "CMP" }
          - { label: "Mixed", value: "MIX" }
      - label: "Opponent"
        name: "opponent"
        widget: "select"
        options:
          - { label: "Ajax", value: "AJX" }
          - { label: "Apollo Ashford", value: "APA" }
          - { label: "Christchurch", value: "CHR" }
          - { label: "Herne Bay", value: "HRN" }
          - { label: "Invicta Pilgrims", value: "INC" }
          - { label: "Kings", value: "KNG" }
          - { label: "Faversham", value: "FAV" }
          - { label: "Hartsdown Park", value: "HRT" }
          - { label: "Racqueteers", value: "RCQ" }
          - { label: "Rovers", value: "ROV" }
          - { label: "Westgate", value: "WST" }
      - label: "Location"
        name: "location"
        widget: "select"
        options:
          - { label: "Home", value: "H" }
          - { label: "Away", value: "A" }